### PR TITLE
Major dependencies and build system upgrade

### PR DESCRIPTION
**Pull request by marmbrus**
- Upgrade deploylib to use the newest mesos protocol (protobuffs)
- Upgrade sbt to 0.11.RC0
- add sbt launcher to scads repo (bin/sbt)
- Integrate sbt and deploylib thought deploy-console task (removes the need for write-packaged-classpath)
- Upgrade to avro 1.6.0-SNAPSHOT
- Fix classloading issues when running tests from sbt (removed dependency on custom sbt)
- Upgrade to scala 2.9.1
- fix piql optimizer test cases
- fix storage engine test cases that depend on valueClass metadata
- add experiment to compare costbased and scale indept plans
- numerous small bug fixes

### CODE REVIEW

**Comment by nicklan** [comment]
Getting the following when trying to compile in sbt09 branch:

```
nick@nick:~/research/SCADS (sbt09)$ ./bin/sbt
[info] Loading project definition from /home/nick/research/SCADS/project/plugins
[info] Set current project to scads (in build file:/home/nick/research/SCADS/)
scads:sbt09> project scala-engine
project scala-engine
[info] Set current project to scala-engine (in build file:/home/nick/research/SCADS/)
scala-engine:sbt09> clean
clean
[success] Total time: 0 s, completed Sep 12, 2011 5:28:06 PM
scala-engine:sbt09> update
update
[info] Updating {file:/home/nick/research/SCADS/}scala-engine...
[info] Done updating.
[success] Total time: 7 s, completed Sep 12, 2011 5:28:14 PM
scala-engine:sbt09> compile
compile
[info] Compiling 22 Scala sources to /home/nick/research/SCADS/deploylib/target/scala-2.9.1/classes...
Warning: could not load descriptor for plugin /home/nick/.ivy2/cache/org.apache.avro/avro/jars/avro-1.6.0-SNAPSHOT.jar
Warning: could not load descriptor for plugin /home/nick/.ivy2/cache/org.codehaus.jackson/jackson-mapper-asl/jars/jackson-mapper-asl-1.7.3.jar
Warning: could not load descriptor for plugin /home/nick/.ivy2/cache/org.codehaus.jackson/jackson-core-asl/jars/jackson-core-asl-1.7.3.jar
Warning: could not load descriptor for plugin /home/nick/.ivy2/cache/com.thoughtworks.paranamer/paranamer/jars/paranamer-2.3.jar
Warning: could not load descriptor for plugin /home/nick/.ivy2/cache/org.xerial.snappy/snappy-java/bundles/snappy-java-1.0.3.2.jar
Warning: could not load descriptor for plugin /home/nick/.ivy2/cache/org.slf4j/slf4j-api/jars/slf4j-api-1.6.1.jar
Warning: could not load descriptor for plugin /home/nick/.ivy2/cache/org.apache.avro/avro-ipc/jars/avro-ipc-1.6.0-SNAPSHOT.jar
Warning: could not load descriptor for plugin /home/nick/.ivy2/cache/org.mortbay.jetty/jetty/jars/jetty-6.1.26.jar
Warning: could not load descriptor for plugin /home/nick/.ivy2/cache/org.mortbay.jetty/jetty-util/jars/jetty-util-6.1.26.jar
Warning: could not load descriptor for plugin /home/nick/.ivy2/cache/org.mortbay.jetty/servlet-api/jars/servlet-api-2.5-20081211.jar
Warning: could not load descriptor for plugin /home/nick/.ivy2/cache/org.jboss.netty/netty/bundles/netty-3.2.4.Final.jar
Warning: could not load descriptor for plugin /home/nick/.ivy2/cache/org.apache.velocity/velocity/jars/velocity-1.7.jar
Warning: could not load descriptor for plugin /home/nick/.ivy2/cache/commons-collections/commons-collections/jars/commons-collections-3.2.1.jar
Warning: could not load descriptor for plugin /home/nick/.ivy2/cache/commons-lang/commons-lang/jars/commons-lang-2.4.jar
Warning: could not load descriptor for plugin /home/nick/.sbt/boot/scala-2.9.1/lib/scala-compiler.jar
Warning: could not load descriptor for plugin /home/nick/.sbt/boot/scala-2.9.1/lib/scala-library.jar
Warning: could not load descriptor for plugin /home/nick/.ivy2/cache/net.lag/configgy/jars/configgy-2.0.0.jar
Warning: could not load descriptor for plugin /home/nick/.ivy2/cache/org.scala-tools.testing/specs_2.8.0/jars/specs_2.8.0-1.6.5.jar
Warning: could not load descriptor for plugin /home/nick/.ivy2/cache/org.scala-tools/vscaladoc/jars/vscaladoc-1.1-md-3.jar
Warning: could not load descriptor for plugin /home/nick/.ivy2/cache/org.scalatest/scalatest_2.9.1/jars/scalatest_2.9.1-1.6.1.jar
Warning: could not load descriptor for plugin /home/nick/.ivy2/cache/junit/junit/jars/junit-4.7.jar
[error] {file:/home/nick/research/SCADS/}deploylib/compile:compile: java.lang.reflect.InvocationTargetException
[error] Total time: 17 s, completed Sep 12, 2011 5:28:34 PM
scala-engine:sbt09> 
```

**Comment by marmbrus** [comment]
Yeah, I'm getting the same issue when compiling on the RCluster.  I believe it is due to a stale version of the compiler plugin being used, but I'm still working on a definitive fix.  You might try running `sbt clean avro-plugin/publish-local update`, then retry compiling.  It would also be useful if you could include the output from `last compile` after a compilation failure.

**Comment by marmbrus** [comment]
I pushed an updated version of the plugin to the Nexus repo.  It now builds and all tests pass on a fresh ec2 instance.

**Comment by nicklan** [comment]
Cool, builds for me now (and much faster!)

Couple of things we may want to fix.
- We have 9 deprecation warnings about using Schema.parse.  For example:
  
  ```
  [warn] /home/nick/research/SCADS/scalaengine/src/main/scala/client/IndexManager.scala:203: method parse in object Schema is deprecated: see corresponding Javadoc for more information.
  [warn]       val ks = Schema.parse(new String(root("%s/keySchema".format(toGlobalName(n.name))).data))
  [warn]                       ^
  ```
  
  I think we can fix all of these by using a Schema.Parser object.  Probably we should just instantiate a static one somewhere so it caches all the named schemas, unless there could be different schemas with the same name.  If we want a new parser everywhere it's just (to fix above):
  
  ```
  val ks = new Schema.Parser().parse(new String(root("%s/keySchema".format(toGlobalName(n.name))).data))
  ```
- The first time I start sbt I get:
  
  ```
  [info] Loading project definition from /home/nick/research/SCADS/project/plugins
  [info] Updating {file:/home/nick/research/SCADS/project/plugins/}default-7ee961...
  [info] Done updating.
  [info] Compiling 1 Scala source to /home/nick/research/SCADS/project/target/scala_2.9.1/classes...
  [warn] there were 2 deprecation warnings; re-run with -deprecation for details
  [warn] one warning found
  ```
  
  After that no more, but I guess there's something deprecated in the project def?
- I get the following warnings pretty often.  Not sure if it's something on my end or something that should be checked in:
  
  ```
  Warning: could not load descriptor for plugin /home/nick/.ivy2/cache/org.apache.avro/avro/jars/avro-1.6.0-SNAPSHOT.jar
  Warning: could not load descriptor for plugin /home/nick/.ivy2/cache/org.codehaus.jackson/jackson-mapper-asl/jars/jackson-mapper-asl-1.7.3.jar
  Warning: could not load descriptor for plugin /home/nick/.ivy2/cache/org.codehaus.jackson/jackson-core-asl/jars/jackson-core-asl-1.7.3.jar
  Warning: could not load descriptor for plugin /home/nick/.ivy2/cache/com.thoughtworks.paranamer/paranamer/jars/paranamer-2.3.jar
  Warning: could not load descriptor for plugin /home/nick/.ivy2/cache/org.xerial.snappy/snappy-java/bundles/snappy-java-1.0.3.2.jar
  Warning: could not load descriptor for plugin /home/nick/.ivy2/cache/org.slf4j/slf4j-api/jars/slf4j-api-1.6.1.jar
  Warning: could not load descriptor for plugin /home/nick/.ivy2/cache/org.apache.avro/avro-ipc/jars/avro-ipc-1.6.0-SNAPSHOT.jar
  Warning: could not load descriptor for plugin /home/nick/.ivy2/cache/org.mortbay.jetty/jetty/jars/jetty-6.1.26.jar
  Warning: could not load descriptor for plugin /home/nick/.ivy2/cache/org.mortbay.jetty/jetty-util/jars/jetty-util-6.1.26.jar
  Warning: could not load descriptor for plugin /home/nick/.ivy2/cache/org.mortbay.jetty/servlet-api/jars/servlet-api-2.5-20081211.jar
  Warning: could not load descriptor for plugin /home/nick/.ivy2/cache/org.jboss.netty/netty/bundles/netty-3.2.4.Final.jar
  Warning: could not load descriptor for plugin /home/nick/.ivy2/cache/org.apache.velocity/velocity/jars/velocity-1.7.jar
  Warning: could not load descriptor for plugin /home/nick/.ivy2/cache/commons-collections/commons-collections/jars/commons-collections-3.2.1.jar
  Warning: could not load descriptor for plugin /home/nick/.ivy2/cache/commons-lang/commons-lang/jars/commons-lang-2.4.jar
  Warning: could not load descriptor for plugin /home/nick/.sbt/boot/scala-2.9.1/lib/scala-compiler.jar
  Warning: could not load descriptor for plugin /home/nick/.sbt/boot/scala-2.9.1/lib/scala-library.jar
  Warning: could not load descriptor for plugin /home/nick/.ivy2/cache/net.lag/configgy/jars/configgy-2.0.0.jar
  Warning: could not load descriptor for plugin /home/nick/.ivy2/cache/org.scala-tools.testing/specs_2.8.0/jars/specs_2.8.0-1.6.5.jar
  Warning: could not load descriptor for plugin /home/nick/.ivy2/cache/org.scala-tools/vscaladoc/jars/vscaladoc-1.1-md-3.jar
  Warning: could not load descriptor for plugin /home/nick/.ivy2/cache/org.scalatest/scalatest_2.9.1/jars/scalatest_2.9.1-1.6.1.jar
  Warning: could not load descriptor for plugin /home/nick/.ivy2/cache/junit/junit/jars/junit-4.7.jar
  ```

**Comment by marmbrus** [comment]
I fixed the `Schema.parse` issues using the `new Schema.Parser().parser(` solution.  I think we will want to eventually support connecting to namespaces with old schemas so this seems like the best option.

Regarding the other deprecations I believe they are in the build file, but I'm not sure how to make it provide more detail.  I vote we ignore this for now.

Regarding the `Warning: could not load descriptor for plugin`:  This is because the only way to add jar files to the compiler plugin class path is with the `-X:plugin` argument.  Mark Harrah (the sbt guy) has filed an [enhancement request with the scala compiler](https://issues.scala-lang.org/browse/SI-4841) to remove this warning, but I think it will be a while before it makes it through the system.

If there are no other suggestions I vote we move forward with the merge.

**Comment by nicklan** [comment]
i vote to go forward as it all seems to work for me now too.

**Comment by marmbrus** [comment]
Okay, I renamed this branch as v2.1.2 and made it the default branch for the repository.  I tagged the old version2.1 branch and deleted all fully merged in topic branches (including partition-refactor).

**Pull request closed without merging**
